### ISSUE TITLE
If checking for extension and filesize, still returning true if one of them is true

### ISSUE THREAD

**Issue by mwq27** [pekebyte/pekeUpload#11]
I have a check for filesize and a check for file extension.  If 1 of those fails, and the other is true, your code still sets canUpload = true, meaning it still tries to upload the file.

**Comment by pekebyte** [comment]
Thanks for reporting that,

Actually after a long time, I decided to improve this script, when I did this, this was my first jQuery plugin, and I was a very javascript novice. I think that this new version has a lot of improvements.
